import type { CryptoPair } from './types';

export const CRYPTO_PAIRS: CryptoPair[] = [
  { base: 'BTC', quote: 'USDT', symbol: 'BTC/USDT' },
  { base: 'ETH', quote: 'USDT', symbol: 'ETH/USDT' },
  { base: 'SOL', quote: 'USDT', symbol: 'SOL/USDT' },
  { base: 'BNB', quote: 'USDT', symbol: 'BNB/USDT' },
  { base: 'XRP', quote: 'USDT', symbol: 'XRP/USDT' },
  { base: 'DOGE', quote: 'USDT', symbol: 'DOGE/USDT' },
  { base: 'ADA', quote: 'USDT', symbol: 'ADA/USDT' },
  { base: 'AVAX', quote: 'USDT', symbol: 'AVAX/USDT' },
  { base: 'SHIB', quote: 'USDT', symbol: 'SHIB/USDT' },
  { base: 'DOT', quote: 'USDT', symbol: 'DOT/USDT' },
  { base: 'LINK', quote: 'USDT', symbol: 'LINK/USDT' },
  { base: 'MATIC', quote: 'USDT', symbol: 'MATIC/USDT' },
  { base: 'TRX', quote: 'USDT', symbol: 'TRX/USDT' },
  { base: 'LTC', quote: 'USDT', symbol: 'LTC/USDT' },
  { base: 'BCH', quote: 'USDT', symbol: 'BCH/USDT' },
  { base: 'TON', quote: 'USDT', symbol: 'TON/USDT' },
  { base: 'NEAR', quote: 'USDT', symbol: 'NEAR/USDT' },
  { base: 'UNI', quote: 'USDT', symbol: 'UNI/USDT' },
  { base: 'ICP', quote: 'USDT', symbol: 'ICP/USDT' },
  { base: 'FIL', quote: 'USDT', symbol: 'FIL/USDT' },
  { base: 'ETC', quote: 'USDT', symbol: 'ETC/USDT' },
  { base: 'XLM', quote: 'USDT', symbol: 'XLM/USDT' },
  { base: 'ATOM', quote: 'USDT', symbol: 'ATOM/USDT' },
  { base: 'HBAR', quote: 'USDT', symbol: 'HBAR/USDT' },
  { base: 'APT', quote: 'USDT', symbol: 'APT/USDT' },
  { base: 'ARB', quote: 'USDT', symbol: 'ARB/USDT' },
  { base: 'VET', quote: 'USDT', symbol: 'VET/USDT' },
  { base: 'OP', quote: 'USDT', symbol: 'OP/USDT' },
  { base: 'AAVE', quote: 'USDT', symbol: 'AAVE/USDT' },
  { base: 'GRT', quote: 'USDT', symbol: 'GRT/USDT' },
  { base: 'FTM', quote: 'USDT', symbol: 'FTM/USDT' },
  { base: 'PEPE', quote: 'USDT', symbol: 'PEPE/USDT' },
  { base: 'RNDR', quote: 'USDT', symbol: 'RNDR/USDT' },
  { base: 'INJ', quote: 'USDT', symbol: 'INJ/USDT' },
  { base: 'MANA', quote: 'USDT', symbol: 'MANA/USDT' },
];

// FIX: Add CURRENCIES
export const CURRENCIES: { code: string; name: string }[] = [
    { code: 'USDT', name: 'Tether' },
    { code: 'USD', name: 'US Dollar' },
    { code: 'EUR', name: 'Euro' },
    { code: 'JPY', name: 'Japanese Yen' },
    { code: 'GBP', name: 'British Pound' },
    { code: 'AUD', name: 'Australian Dollar' },
    { code: 'CAD', name: 'Canadian Dollar' },
    { code: 'CHF', name: 'Swiss Franc' },
];

// FIX: Add CRYPTO_ASSETS
export const CRYPTO_ASSETS: { code: string; name: string }[] = [
  { code: 'BTC', name: 'Bitcoin' },
  { code: 'ETH', name: 'Ethereum' },
  { code: 'SOL', name: 'Solana' },
  { code: 'BNB', name: 'Binance Coin' },
  { code: 'XRP', name: 'Ripple' },
  { code: 'DOGE', name: 'Dogecoin' },
  { code: 'ADA', name: 'Cardano' },
  { code: 'AVAX', name: 'Avalanche' },
  { code: 'SHIB', name: 'Shiba Inu' },
  { code: 'DOT', name: 'Polkadot' },
  { code: 'LINK', name: 'Chainlink' },
  { code: 'MATIC', name: 'Polygon' },
  { code: 'TRX', name: 'Tron' },
  { code: 'LTC', name: 'Litecoin' },
  { code: 'BCH', name: 'Bitcoin Cash' },
  { code: 'TON', name: 'Toncoin' },
  { code: 'NEAR', name: 'Near Protocol' },
  { code: 'UNI', name: 'Uniswap' },
  { code: 'ICP', name: 'Internet Computer' },
  { code: 'FIL', name: 'Filecoin' },
  { code: 'ETC', name: 'Ethereum Classic' },
  { code: 'XLM', name: 'Stellar' },
  { code: 'ATOM', name: 'Cosmos' },
  { code: 'HBAR', name: 'Hedera' },
  { code: 'APT', name: 'Aptos' },
  { code: 'ARB', name: 'Arbitrum' },
  { code: 'VET', name: 'VeChain' },
  { code: 'OP', name: 'Optimism' },
  { code: 'AAVE', name: 'Aave' },
  { code: 'GRT', name: 'The Graph' },
  { code: 'FTM', name: 'Fantom' },
  { code: 'PEPE', name: 'Pepe' },
  { code: 'RNDR', name: 'Render' },
  { code: 'INJ', name: 'Injective' },
  { code: 'MANA', name: 'Decentraland' },
];